// keywords.cpp — Keyword lookup table for the SQL scanner.
//
// Converted from PostgreSQL 15's src/include/parser/kwlist.h.
// All 460 keywords are listed in ASCII order for binary search.

#include "mytoydb/parser/keywords.h"

#include "gram.tab.hpp"

namespace mytoydb::parser {

const KeywordEntry kKeywordTable[] = {
    {"abort", mytoydb_parser::BisonParser::token::ABORT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"absolute", mytoydb_parser::BisonParser::token::ABSOLUTE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"access", mytoydb_parser::BisonParser::token::ACCESS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"action", mytoydb_parser::BisonParser::token::ACTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"add", mytoydb_parser::BisonParser::token::ADD_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"admin", mytoydb_parser::BisonParser::token::ADMIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"after", mytoydb_parser::BisonParser::token::AFTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"aggregate", mytoydb_parser::BisonParser::token::AGGREGATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"all", mytoydb_parser::BisonParser::token::ALL, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"also", mytoydb_parser::BisonParser::token::ALSO, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"alter", mytoydb_parser::BisonParser::token::ALTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"always", mytoydb_parser::BisonParser::token::ALWAYS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"analyse", mytoydb_parser::BisonParser::token::ANALYSE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"analyze", mytoydb_parser::BisonParser::token::ANALYZE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"and", mytoydb_parser::BisonParser::token::AND, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"any", mytoydb_parser::BisonParser::token::ANY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"array", mytoydb_parser::BisonParser::token::ARRAY, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"as", mytoydb_parser::BisonParser::token::AS, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"asc", mytoydb_parser::BisonParser::token::ASC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"asensitive", mytoydb_parser::BisonParser::token::ASENSITIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"assertion", mytoydb_parser::BisonParser::token::ASSERTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"assignment", mytoydb_parser::BisonParser::token::ASSIGNMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"asymmetric", mytoydb_parser::BisonParser::token::ASYMMETRIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"at", mytoydb_parser::BisonParser::token::AT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"atomic", mytoydb_parser::BisonParser::token::ATOMIC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"attach", mytoydb_parser::BisonParser::token::ATTACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"attribute", mytoydb_parser::BisonParser::token::ATTRIBUTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"authorization", mytoydb_parser::BisonParser::token::AUTHORIZATION,
     KeywordCategory::kTypeFuncName, KeywordLabel::kBareLabel},
    {"backward", mytoydb_parser::BisonParser::token::BACKWARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"before", mytoydb_parser::BisonParser::token::BEFORE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"begin", mytoydb_parser::BisonParser::token::BEGIN_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"between", mytoydb_parser::BisonParser::token::BETWEEN, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"bigint", mytoydb_parser::BisonParser::token::BIGINT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"binary", mytoydb_parser::BisonParser::token::BINARY, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"bit", mytoydb_parser::BisonParser::token::BIT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"boolean", mytoydb_parser::BisonParser::token::BOOLEAN_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"both", mytoydb_parser::BisonParser::token::BOTH, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"breadth", mytoydb_parser::BisonParser::token::BREADTH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"by", mytoydb_parser::BisonParser::token::BY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cache", mytoydb_parser::BisonParser::token::CACHE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"call", mytoydb_parser::BisonParser::token::CALL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"called", mytoydb_parser::BisonParser::token::CALLED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cascade", mytoydb_parser::BisonParser::token::CASCADE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cascaded", mytoydb_parser::BisonParser::token::CASCADED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"case", mytoydb_parser::BisonParser::token::CASE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"cast", mytoydb_parser::BisonParser::token::CAST, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"catalog", mytoydb_parser::BisonParser::token::CATALOG_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"chain", mytoydb_parser::BisonParser::token::CHAIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"char", mytoydb_parser::BisonParser::token::CHAR_P, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"character", mytoydb_parser::BisonParser::token::CHARACTER, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"characteristics", mytoydb_parser::BisonParser::token::CHARACTERISTICS,
     KeywordCategory::kUnreserved, KeywordLabel::kBareLabel},
    {"check", mytoydb_parser::BisonParser::token::CHECK, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"checkpoint", mytoydb_parser::BisonParser::token::CHECKPOINT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"class", mytoydb_parser::BisonParser::token::CLASS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"close", mytoydb_parser::BisonParser::token::CLOSE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cluster", mytoydb_parser::BisonParser::token::CLUSTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"coalesce", mytoydb_parser::BisonParser::token::COALESCE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"collate", mytoydb_parser::BisonParser::token::COLLATE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"collation", mytoydb_parser::BisonParser::token::COLLATION, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"column", mytoydb_parser::BisonParser::token::COLUMN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"columns", mytoydb_parser::BisonParser::token::COLUMNS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"comment", mytoydb_parser::BisonParser::token::COMMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"comments", mytoydb_parser::BisonParser::token::COMMENTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"commit", mytoydb_parser::BisonParser::token::COMMIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"committed", mytoydb_parser::BisonParser::token::COMMITTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"compression", mytoydb_parser::BisonParser::token::COMPRESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"concurrently", mytoydb_parser::BisonParser::token::CONCURRENTLY,
     KeywordCategory::kTypeFuncName, KeywordLabel::kBareLabel},
    {"configuration", mytoydb_parser::BisonParser::token::CONFIGURATION,
     KeywordCategory::kUnreserved, KeywordLabel::kBareLabel},
    {"conflict", mytoydb_parser::BisonParser::token::CONFLICT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"connection", mytoydb_parser::BisonParser::token::CONNECTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"constraint", mytoydb_parser::BisonParser::token::CONSTRAINT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"constraints", mytoydb_parser::BisonParser::token::CONSTRAINTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"content", mytoydb_parser::BisonParser::token::CONTENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"continue", mytoydb_parser::BisonParser::token::CONTINUE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"conversion", mytoydb_parser::BisonParser::token::CONVERSION_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"copy", mytoydb_parser::BisonParser::token::COPY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cost", mytoydb_parser::BisonParser::token::COST, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"create", mytoydb_parser::BisonParser::token::CREATE, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"createdb", mytoydb_parser::BisonParser::token::CREATEDB, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"createrole", mytoydb_parser::BisonParser::token::CREATEROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cross", mytoydb_parser::BisonParser::token::CROSS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"csv", mytoydb_parser::BisonParser::token::CSV, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cube", mytoydb_parser::BisonParser::token::CUBE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"current", mytoydb_parser::BisonParser::token::CURRENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"current_catalog", mytoydb_parser::BisonParser::token::CURRENT_CATALOG,
     KeywordCategory::kReserved, KeywordLabel::kBareLabel},
    {"current_date", mytoydb_parser::BisonParser::token::CURRENT_DATE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_role", mytoydb_parser::BisonParser::token::CURRENT_ROLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_schema", mytoydb_parser::BisonParser::token::CURRENT_SCHEMA,
     KeywordCategory::kTypeFuncName, KeywordLabel::kBareLabel},
    {"current_time", mytoydb_parser::BisonParser::token::CURRENT_TIME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_timestamp", mytoydb_parser::BisonParser::token::CURRENT_TIMESTAMP,
     KeywordCategory::kReserved, KeywordLabel::kBareLabel},
    {"current_user", mytoydb_parser::BisonParser::token::CURRENT_USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"cursor", mytoydb_parser::BisonParser::token::CURSOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cycle", mytoydb_parser::BisonParser::token::CYCLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"data", mytoydb_parser::BisonParser::token::DATA_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"database", mytoydb_parser::BisonParser::token::DATABASE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"day", mytoydb_parser::BisonParser::token::DAY_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"deallocate", mytoydb_parser::BisonParser::token::DEALLOCATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"dec", mytoydb_parser::BisonParser::token::DEC, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"decimal", mytoydb_parser::BisonParser::token::DECIMAL_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"declare", mytoydb_parser::BisonParser::token::DECLARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"default", mytoydb_parser::BisonParser::token::DEFAULT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"defaults", mytoydb_parser::BisonParser::token::DEFAULTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"deferrable", mytoydb_parser::BisonParser::token::DEFERRABLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"deferred", mytoydb_parser::BisonParser::token::DEFERRED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"definer", mytoydb_parser::BisonParser::token::DEFINER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delete", mytoydb_parser::BisonParser::token::DELETE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delimiter", mytoydb_parser::BisonParser::token::DELIMITER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delimiters", mytoydb_parser::BisonParser::token::DELIMITERS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"depends", mytoydb_parser::BisonParser::token::DEPENDS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"depth", mytoydb_parser::BisonParser::token::DEPTH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"desc", mytoydb_parser::BisonParser::token::DESC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"detach", mytoydb_parser::BisonParser::token::DETACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"dictionary", mytoydb_parser::BisonParser::token::DICTIONARY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"disable", mytoydb_parser::BisonParser::token::DISABLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"discard", mytoydb_parser::BisonParser::token::DISCARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"distinct", mytoydb_parser::BisonParser::token::DISTINCT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"do", mytoydb_parser::BisonParser::token::DO, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"document", mytoydb_parser::BisonParser::token::DOCUMENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"domain", mytoydb_parser::BisonParser::token::DOMAIN_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"double", mytoydb_parser::BisonParser::token::DOUBLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"drop", mytoydb_parser::BisonParser::token::DROP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"each", mytoydb_parser::BisonParser::token::EACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"else", mytoydb_parser::BisonParser::token::ELSE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"enable", mytoydb_parser::BisonParser::token::ENABLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"encoding", mytoydb_parser::BisonParser::token::ENCODING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"encrypted", mytoydb_parser::BisonParser::token::ENCRYPTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"end", mytoydb_parser::BisonParser::token::END_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"enum", mytoydb_parser::BisonParser::token::ENUM_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"escape", mytoydb_parser::BisonParser::token::ESCAPE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"event", mytoydb_parser::BisonParser::token::EVENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"except", mytoydb_parser::BisonParser::token::EXCEPT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"exclude", mytoydb_parser::BisonParser::token::EXCLUDE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"excluding", mytoydb_parser::BisonParser::token::EXCLUDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"exclusive", mytoydb_parser::BisonParser::token::EXCLUSIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"execute", mytoydb_parser::BisonParser::token::EXECUTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"exists", mytoydb_parser::BisonParser::token::EXISTS, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"explain", mytoydb_parser::BisonParser::token::EXPLAIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"expression", mytoydb_parser::BisonParser::token::EXPRESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"extension", mytoydb_parser::BisonParser::token::EXTENSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"external", mytoydb_parser::BisonParser::token::EXTERNAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"extract", mytoydb_parser::BisonParser::token::EXTRACT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"false", mytoydb_parser::BisonParser::token::FALSE_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"family", mytoydb_parser::BisonParser::token::FAMILY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"fetch", mytoydb_parser::BisonParser::token::FETCH, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"filter", mytoydb_parser::BisonParser::token::FILTER, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"finalize", mytoydb_parser::BisonParser::token::FINALIZE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"first", mytoydb_parser::BisonParser::token::FIRST_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"float", mytoydb_parser::BisonParser::token::FLOAT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"following", mytoydb_parser::BisonParser::token::FOLLOWING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"for", mytoydb_parser::BisonParser::token::FOR, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"force", mytoydb_parser::BisonParser::token::FORCE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"foreign", mytoydb_parser::BisonParser::token::FOREIGN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"forward", mytoydb_parser::BisonParser::token::FORWARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"freeze", mytoydb_parser::BisonParser::token::FREEZE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"from", mytoydb_parser::BisonParser::token::FROM, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"full", mytoydb_parser::BisonParser::token::FULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"function", mytoydb_parser::BisonParser::token::FUNCTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"functions", mytoydb_parser::BisonParser::token::FUNCTIONS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"generated", mytoydb_parser::BisonParser::token::GENERATED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"global", mytoydb_parser::BisonParser::token::GLOBAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"grant", mytoydb_parser::BisonParser::token::GRANT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"granted", mytoydb_parser::BisonParser::token::GRANTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"greatest", mytoydb_parser::BisonParser::token::GREATEST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"group", mytoydb_parser::BisonParser::token::GROUP_P, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"grouping", mytoydb_parser::BisonParser::token::GROUPING, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"groups", mytoydb_parser::BisonParser::token::GROUPS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"handler", mytoydb_parser::BisonParser::token::HANDLER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"having", mytoydb_parser::BisonParser::token::HAVING, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"header", mytoydb_parser::BisonParser::token::HEADER_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"hold", mytoydb_parser::BisonParser::token::HOLD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"hour", mytoydb_parser::BisonParser::token::HOUR_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"identity", mytoydb_parser::BisonParser::token::IDENTITY_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"if", mytoydb_parser::BisonParser::token::IF_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"ilike", mytoydb_parser::BisonParser::token::ILIKE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"immediate", mytoydb_parser::BisonParser::token::IMMEDIATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"immutable", mytoydb_parser::BisonParser::token::IMMUTABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"implicit", mytoydb_parser::BisonParser::token::IMPLICIT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"import", mytoydb_parser::BisonParser::token::IMPORT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"in", mytoydb_parser::BisonParser::token::IN_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"include", mytoydb_parser::BisonParser::token::INCLUDE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"including", mytoydb_parser::BisonParser::token::INCLUDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"increment", mytoydb_parser::BisonParser::token::INCREMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"index", mytoydb_parser::BisonParser::token::INDEX, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"indexes", mytoydb_parser::BisonParser::token::INDEXES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inherit", mytoydb_parser::BisonParser::token::INHERIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inherits", mytoydb_parser::BisonParser::token::INHERITS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"initially", mytoydb_parser::BisonParser::token::INITIALLY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"inline", mytoydb_parser::BisonParser::token::INLINE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inner", mytoydb_parser::BisonParser::token::INNER_P, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"inout", mytoydb_parser::BisonParser::token::INOUT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"input", mytoydb_parser::BisonParser::token::INPUT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"insensitive", mytoydb_parser::BisonParser::token::INSENSITIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"insert", mytoydb_parser::BisonParser::token::INSERT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"instead", mytoydb_parser::BisonParser::token::INSTEAD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"int", mytoydb_parser::BisonParser::token::INT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"integer", mytoydb_parser::BisonParser::token::INTEGER, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"intersect", mytoydb_parser::BisonParser::token::INTERSECT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"interval", mytoydb_parser::BisonParser::token::INTERVAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"into", mytoydb_parser::BisonParser::token::INTO, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"invoker", mytoydb_parser::BisonParser::token::INVOKER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"is", mytoydb_parser::BisonParser::token::IS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"isnull", mytoydb_parser::BisonParser::token::ISNULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"isolation", mytoydb_parser::BisonParser::token::ISOLATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"join", mytoydb_parser::BisonParser::token::JOIN, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"key", mytoydb_parser::BisonParser::token::KEY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"label", mytoydb_parser::BisonParser::token::LABEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"language", mytoydb_parser::BisonParser::token::LANGUAGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"large", mytoydb_parser::BisonParser::token::LARGE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"last", mytoydb_parser::BisonParser::token::LAST_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"lateral", mytoydb_parser::BisonParser::token::LATERAL_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"leading", mytoydb_parser::BisonParser::token::LEADING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"leakproof", mytoydb_parser::BisonParser::token::LEAKPROOF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"least", mytoydb_parser::BisonParser::token::LEAST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"left", mytoydb_parser::BisonParser::token::LEFT, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"level", mytoydb_parser::BisonParser::token::LEVEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"like", mytoydb_parser::BisonParser::token::LIKE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"limit", mytoydb_parser::BisonParser::token::LIMIT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"listen", mytoydb_parser::BisonParser::token::LISTEN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"load", mytoydb_parser::BisonParser::token::LOAD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"local", mytoydb_parser::BisonParser::token::LOCAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"localtime", mytoydb_parser::BisonParser::token::LOCALTIME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"localtimestamp", mytoydb_parser::BisonParser::token::LOCALTIMESTAMP,
     KeywordCategory::kReserved, KeywordLabel::kBareLabel},
    {"location", mytoydb_parser::BisonParser::token::LOCATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"lock", mytoydb_parser::BisonParser::token::LOCK_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"locked", mytoydb_parser::BisonParser::token::LOCKED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"logged", mytoydb_parser::BisonParser::token::LOGGED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"login", mytoydb_parser::BisonParser::token::LOGIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"mapping", mytoydb_parser::BisonParser::token::MAPPING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"match", mytoydb_parser::BisonParser::token::MATCH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"matched", mytoydb_parser::BisonParser::token::MATCHED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"materialized", mytoydb_parser::BisonParser::token::MATERIALIZED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"maxvalue", mytoydb_parser::BisonParser::token::MAXVALUE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"merge", mytoydb_parser::BisonParser::token::MERGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"method", mytoydb_parser::BisonParser::token::METHOD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"minute", mytoydb_parser::BisonParser::token::MINUTE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"minvalue", mytoydb_parser::BisonParser::token::MINVALUE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"mode", mytoydb_parser::BisonParser::token::MODE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"month", mytoydb_parser::BisonParser::token::MONTH_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"move", mytoydb_parser::BisonParser::token::MOVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"name", mytoydb_parser::BisonParser::token::NAME_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"names", mytoydb_parser::BisonParser::token::NAMES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"national", mytoydb_parser::BisonParser::token::NATIONAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"natural", mytoydb_parser::BisonParser::token::NATURAL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"nchar", mytoydb_parser::BisonParser::token::NCHAR, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"new", mytoydb_parser::BisonParser::token::NEW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"next", mytoydb_parser::BisonParser::token::NEXT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfc", mytoydb_parser::BisonParser::token::NFC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfd", mytoydb_parser::BisonParser::token::NFD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfkc", mytoydb_parser::BisonParser::token::NFKC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfkd", mytoydb_parser::BisonParser::token::NFKD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"no", mytoydb_parser::BisonParser::token::NO, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nocreatedb", mytoydb_parser::BisonParser::token::NOCREATEDB, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nocreaterole", mytoydb_parser::BisonParser::token::NOCREATEROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"noreplication", mytoydb_parser::BisonParser::token::NOREPLICATION,
     KeywordCategory::kUnreserved, KeywordLabel::kBareLabel},
    {"nosuperuser", mytoydb_parser::BisonParser::token::NOSUPERUSER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"none", mytoydb_parser::BisonParser::token::NONE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"normalize", mytoydb_parser::BisonParser::token::NORMALIZE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"normalized", mytoydb_parser::BisonParser::token::NORMALIZED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"not", mytoydb_parser::BisonParser::token::NOT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"nothing", mytoydb_parser::BisonParser::token::NOTHING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"notify", mytoydb_parser::BisonParser::token::NOTIFY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"notnull", mytoydb_parser::BisonParser::token::NOTNULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"nowait", mytoydb_parser::BisonParser::token::NOWAIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"null", mytoydb_parser::BisonParser::token::NULL_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"nullif", mytoydb_parser::BisonParser::token::NULLIF, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"nulls", mytoydb_parser::BisonParser::token::NULLS_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"numeric", mytoydb_parser::BisonParser::token::NUMERIC, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"object", mytoydb_parser::BisonParser::token::OBJECT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"of", mytoydb_parser::BisonParser::token::OF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"off", mytoydb_parser::BisonParser::token::OFF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"offset", mytoydb_parser::BisonParser::token::OFFSET, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"oids", mytoydb_parser::BisonParser::token::OIDS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"old", mytoydb_parser::BisonParser::token::OLD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"on", mytoydb_parser::BisonParser::token::ON, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"only", mytoydb_parser::BisonParser::token::ONLY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"operator", mytoydb_parser::BisonParser::token::OPERATOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"option", mytoydb_parser::BisonParser::token::OPTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"options", mytoydb_parser::BisonParser::token::OPTIONS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"or", mytoydb_parser::BisonParser::token::OR, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"order", mytoydb_parser::BisonParser::token::ORDER, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"ordinality", mytoydb_parser::BisonParser::token::ORDINALITY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"others", mytoydb_parser::BisonParser::token::OTHERS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"out", mytoydb_parser::BisonParser::token::OUT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"outer", mytoydb_parser::BisonParser::token::OUTER_P, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"over", mytoydb_parser::BisonParser::token::OVER, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"overlaps", mytoydb_parser::BisonParser::token::OVERLAPS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"overlay", mytoydb_parser::BisonParser::token::OVERLAY, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"overriding", mytoydb_parser::BisonParser::token::OVERRIDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"owned", mytoydb_parser::BisonParser::token::OWNED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"owner", mytoydb_parser::BisonParser::token::OWNER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parallel", mytoydb_parser::BisonParser::token::PARALLEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parameter", mytoydb_parser::BisonParser::token::PARAMETER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parser", mytoydb_parser::BisonParser::token::PARSER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"partial", mytoydb_parser::BisonParser::token::PARTIAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"partition", mytoydb_parser::BisonParser::token::PARTITION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"passing", mytoydb_parser::BisonParser::token::PASSING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"password", mytoydb_parser::BisonParser::token::PASSWORD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"placing", mytoydb_parser::BisonParser::token::PLACING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"plans", mytoydb_parser::BisonParser::token::PLANS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"policy", mytoydb_parser::BisonParser::token::POLICY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"position", mytoydb_parser::BisonParser::token::POSITION, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"preceding", mytoydb_parser::BisonParser::token::PRECEDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"precision", mytoydb_parser::BisonParser::token::PRECISION, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"prepare", mytoydb_parser::BisonParser::token::PREPARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"prepared", mytoydb_parser::BisonParser::token::PREPARED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"preserve", mytoydb_parser::BisonParser::token::PRESERVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"primary", mytoydb_parser::BisonParser::token::PRIMARY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"prior", mytoydb_parser::BisonParser::token::PRIOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"privileges", mytoydb_parser::BisonParser::token::PRIVILEGES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedural", mytoydb_parser::BisonParser::token::PROCEDURAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedure", mytoydb_parser::BisonParser::token::PROCEDURE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedures", mytoydb_parser::BisonParser::token::PROCEDURES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"program", mytoydb_parser::BisonParser::token::PROGRAM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"publication", mytoydb_parser::BisonParser::token::PUBLICATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"quote", mytoydb_parser::BisonParser::token::QUOTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"range", mytoydb_parser::BisonParser::token::RANGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"read", mytoydb_parser::BisonParser::token::READ, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"real", mytoydb_parser::BisonParser::token::REAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"reassign", mytoydb_parser::BisonParser::token::REASSIGN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"recheck", mytoydb_parser::BisonParser::token::RECHECK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"recursive", mytoydb_parser::BisonParser::token::RECURSIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"ref", mytoydb_parser::BisonParser::token::REF_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"references", mytoydb_parser::BisonParser::token::REFERENCES, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"referencing", mytoydb_parser::BisonParser::token::REFERENCING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"refresh", mytoydb_parser::BisonParser::token::REFRESH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"reindex", mytoydb_parser::BisonParser::token::REINDEX, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"relative", mytoydb_parser::BisonParser::token::RELATIVE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"release", mytoydb_parser::BisonParser::token::RELEASE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rename", mytoydb_parser::BisonParser::token::RENAME, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"repeatable", mytoydb_parser::BisonParser::token::REPEATABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replace", mytoydb_parser::BisonParser::token::REPLACE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replica", mytoydb_parser::BisonParser::token::REPLICA, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replication", mytoydb_parser::BisonParser::token::REPLICATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"reset", mytoydb_parser::BisonParser::token::RESET, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"restart", mytoydb_parser::BisonParser::token::RESTART, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"restrict", mytoydb_parser::BisonParser::token::RESTRICT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"return", mytoydb_parser::BisonParser::token::RETURN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"returning", mytoydb_parser::BisonParser::token::RETURNING, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"returns", mytoydb_parser::BisonParser::token::RETURNS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"revoke", mytoydb_parser::BisonParser::token::REVOKE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"right", mytoydb_parser::BisonParser::token::RIGHT, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"role", mytoydb_parser::BisonParser::token::ROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rollback", mytoydb_parser::BisonParser::token::ROLLBACK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rollup", mytoydb_parser::BisonParser::token::ROLLUP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"routine", mytoydb_parser::BisonParser::token::ROUTINE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"routines", mytoydb_parser::BisonParser::token::ROUTINES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"row", mytoydb_parser::BisonParser::token::ROW, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"rows", mytoydb_parser::BisonParser::token::ROWS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rule", mytoydb_parser::BisonParser::token::RULE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"savepoint", mytoydb_parser::BisonParser::token::SAVEPOINT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"schema", mytoydb_parser::BisonParser::token::SCHEMA, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"schemas", mytoydb_parser::BisonParser::token::SCHEMAS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"scroll", mytoydb_parser::BisonParser::token::SCROLL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"search", mytoydb_parser::BisonParser::token::SEARCH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"second", mytoydb_parser::BisonParser::token::SECOND_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"security", mytoydb_parser::BisonParser::token::SECURITY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"select", mytoydb_parser::BisonParser::token::SELECT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sequence", mytoydb_parser::BisonParser::token::SEQUENCE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"sequences", mytoydb_parser::BisonParser::token::SEQUENCES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"serializable", mytoydb_parser::BisonParser::token::SERIALIZABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"server", mytoydb_parser::BisonParser::token::SERVER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"session", mytoydb_parser::BisonParser::token::SESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"session_user", mytoydb_parser::BisonParser::token::SESSION_USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"set", mytoydb_parser::BisonParser::token::SET, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"setof", mytoydb_parser::BisonParser::token::SETOF, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"sets", mytoydb_parser::BisonParser::token::SETS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"share", mytoydb_parser::BisonParser::token::SHARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"show", mytoydb_parser::BisonParser::token::SHOW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"similar", mytoydb_parser::BisonParser::token::SIMILAR, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"simple", mytoydb_parser::BisonParser::token::SIMPLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"skip", mytoydb_parser::BisonParser::token::SKIP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"smallint", mytoydb_parser::BisonParser::token::SMALLINT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"snapshot", mytoydb_parser::BisonParser::token::SNAPSHOT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"some", mytoydb_parser::BisonParser::token::SOME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sql", mytoydb_parser::BisonParser::token::SQL_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stable", mytoydb_parser::BisonParser::token::STABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"standalone", mytoydb_parser::BisonParser::token::STANDALONE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"start", mytoydb_parser::BisonParser::token::START, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"statement", mytoydb_parser::BisonParser::token::STATEMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"statistics", mytoydb_parser::BisonParser::token::STATISTICS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stdin", mytoydb_parser::BisonParser::token::STDIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stdout", mytoydb_parser::BisonParser::token::STDOUT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"storage", mytoydb_parser::BisonParser::token::STORAGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stored", mytoydb_parser::BisonParser::token::STORED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"strict", mytoydb_parser::BisonParser::token::STRICT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"strip", mytoydb_parser::BisonParser::token::STRIP_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"subscription", mytoydb_parser::BisonParser::token::SUBSCRIPTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"substring", mytoydb_parser::BisonParser::token::SUBSTRING, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"support", mytoydb_parser::BisonParser::token::SUPPORT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"superuser", mytoydb_parser::BisonParser::token::SUPERUSER_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"symmetric", mytoydb_parser::BisonParser::token::SYMMETRIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sysid", mytoydb_parser::BisonParser::token::SYSID, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"system", mytoydb_parser::BisonParser::token::SYSTEM_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"table", mytoydb_parser::BisonParser::token::TABLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"tables", mytoydb_parser::BisonParser::token::TABLES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"tablesample", mytoydb_parser::BisonParser::token::TABLESAMPLE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"tablespace", mytoydb_parser::BisonParser::token::TABLESPACE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"temp", mytoydb_parser::BisonParser::token::TEMP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"template", mytoydb_parser::BisonParser::token::TEMPLATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"temporary", mytoydb_parser::BisonParser::token::TEMPORARY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"text", mytoydb_parser::BisonParser::token::TEXT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"then", mytoydb_parser::BisonParser::token::THEN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"ties", mytoydb_parser::BisonParser::token::TIES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"time", mytoydb_parser::BisonParser::token::TIME, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"timestamp", mytoydb_parser::BisonParser::token::TIMESTAMP, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"to", mytoydb_parser::BisonParser::token::TO, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"trailing", mytoydb_parser::BisonParser::token::TRAILING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"transaction", mytoydb_parser::BisonParser::token::TRANSACTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"transform", mytoydb_parser::BisonParser::token::TRANSFORM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"treat", mytoydb_parser::BisonParser::token::TREAT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"trigger", mytoydb_parser::BisonParser::token::TRIGGER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"trim", mytoydb_parser::BisonParser::token::TRIM, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"true", mytoydb_parser::BisonParser::token::TRUE_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"truncate", mytoydb_parser::BisonParser::token::TRUNCATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"trusted", mytoydb_parser::BisonParser::token::TRUSTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"type", mytoydb_parser::BisonParser::token::TYPE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"types", mytoydb_parser::BisonParser::token::TYPES_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"uescape", mytoydb_parser::BisonParser::token::UESCAPE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unbounded", mytoydb_parser::BisonParser::token::UNBOUNDED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"uncommitted", mytoydb_parser::BisonParser::token::UNCOMMITTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unencrypted", mytoydb_parser::BisonParser::token::UNENCRYPTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"union", mytoydb_parser::BisonParser::token::UNION, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"unique", mytoydb_parser::BisonParser::token::UNIQUE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"unknown", mytoydb_parser::BisonParser::token::UNKNOWN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unlisten", mytoydb_parser::BisonParser::token::UNLISTEN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unlogged", mytoydb_parser::BisonParser::token::UNLOGGED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"until", mytoydb_parser::BisonParser::token::UNTIL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"update", mytoydb_parser::BisonParser::token::UPDATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"user", mytoydb_parser::BisonParser::token::USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"using", mytoydb_parser::BisonParser::token::USING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"vacuum", mytoydb_parser::BisonParser::token::VACUUM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"valid", mytoydb_parser::BisonParser::token::VALID, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"validate", mytoydb_parser::BisonParser::token::VALIDATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"validator", mytoydb_parser::BisonParser::token::VALIDATOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"value", mytoydb_parser::BisonParser::token::VALUE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"values", mytoydb_parser::BisonParser::token::VALUES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"varchar", mytoydb_parser::BisonParser::token::VARCHAR, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"variadic", mytoydb_parser::BisonParser::token::VARIADIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"varying", mytoydb_parser::BisonParser::token::VARYING, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"verbose", mytoydb_parser::BisonParser::token::VERBOSE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"version", mytoydb_parser::BisonParser::token::VERSION_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"view", mytoydb_parser::BisonParser::token::VIEW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"views", mytoydb_parser::BisonParser::token::VIEWS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"volatile", mytoydb_parser::BisonParser::token::VOLATILE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"when", mytoydb_parser::BisonParser::token::WHEN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"where", mytoydb_parser::BisonParser::token::WHERE, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"whitespace", mytoydb_parser::BisonParser::token::WHITESPACE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"window", mytoydb_parser::BisonParser::token::WINDOW, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"with", mytoydb_parser::BisonParser::token::WITH, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"within", mytoydb_parser::BisonParser::token::WITHIN, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"without", mytoydb_parser::BisonParser::token::WITHOUT, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"work", mytoydb_parser::BisonParser::token::WORK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"wrapper", mytoydb_parser::BisonParser::token::WRAPPER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"write", mytoydb_parser::BisonParser::token::WRITE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"xml", mytoydb_parser::BisonParser::token::XML_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"xmlattributes", mytoydb_parser::BisonParser::token::XMLATTRIBUTES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlconcat", mytoydb_parser::BisonParser::token::XMLCONCAT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlelement", mytoydb_parser::BisonParser::token::XMLELEMENT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlexists", mytoydb_parser::BisonParser::token::XMLEXISTS, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlforest", mytoydb_parser::BisonParser::token::XMLFOREST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlnamespaces", mytoydb_parser::BisonParser::token::XMLNAMESPACES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlparse", mytoydb_parser::BisonParser::token::XMLPARSE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlpi", mytoydb_parser::BisonParser::token::XMLPI, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlroot", mytoydb_parser::BisonParser::token::XMLROOT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlserialize", mytoydb_parser::BisonParser::token::XMLSERIALIZE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmltable", mytoydb_parser::BisonParser::token::XMLTABLE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"year", mytoydb_parser::BisonParser::token::YEAR_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"yes", mytoydb_parser::BisonParser::token::YES_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"zone", mytoydb_parser::BisonParser::token::ZONE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
};

const KeywordEntry* ScanKeywordLookup(std::string_view name) {
    int lo = 0, hi = kKeywordCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = name.compare(kKeywordTable[mid].name);
        if (cmp == 0)
            return &kKeywordTable[mid];
        if (cmp < 0)
            hi = mid - 1;
        else
            lo = mid + 1;
    }
    return nullptr;
}

}  // namespace mytoydb::parser
