// keywords.cpp — Keyword lookup table for the SQL scanner.
//
// Converted from PostgreSQL 15's src/include/parser/kwlist.h.
// All 460 keywords are listed in ASCII order for binary search.

#include "parser/keywords.hpp"

#include "gram.tab.hpp"

namespace pgcpp::parser {

const KeywordEntry kKeywordTable[] = {
    {"abort", pgcpp_parser::BisonParser::token::ABORT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"absolute", pgcpp_parser::BisonParser::token::ABSOLUTE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"access", pgcpp_parser::BisonParser::token::ACCESS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"action", pgcpp_parser::BisonParser::token::ACTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"add", pgcpp_parser::BisonParser::token::ADD_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"admin", pgcpp_parser::BisonParser::token::ADMIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"after", pgcpp_parser::BisonParser::token::AFTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"aggregate", pgcpp_parser::BisonParser::token::AGGREGATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"all", pgcpp_parser::BisonParser::token::ALL, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"also", pgcpp_parser::BisonParser::token::ALSO, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"alter", pgcpp_parser::BisonParser::token::ALTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"always", pgcpp_parser::BisonParser::token::ALWAYS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"analyse", pgcpp_parser::BisonParser::token::ANALYSE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"analyze", pgcpp_parser::BisonParser::token::ANALYZE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"and", pgcpp_parser::BisonParser::token::AND, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"any", pgcpp_parser::BisonParser::token::ANY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"array", pgcpp_parser::BisonParser::token::ARRAY, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"as", pgcpp_parser::BisonParser::token::AS, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"asc", pgcpp_parser::BisonParser::token::ASC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"asensitive", pgcpp_parser::BisonParser::token::ASENSITIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"assertion", pgcpp_parser::BisonParser::token::ASSERTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"assignment", pgcpp_parser::BisonParser::token::ASSIGNMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"asymmetric", pgcpp_parser::BisonParser::token::ASYMMETRIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"at", pgcpp_parser::BisonParser::token::AT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"atomic", pgcpp_parser::BisonParser::token::ATOMIC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"attach", pgcpp_parser::BisonParser::token::ATTACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"attribute", pgcpp_parser::BisonParser::token::ATTRIBUTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"authorization", pgcpp_parser::BisonParser::token::AUTHORIZATION,
     KeywordCategory::kTypeFuncName, KeywordLabel::kBareLabel},
    {"backward", pgcpp_parser::BisonParser::token::BACKWARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"before", pgcpp_parser::BisonParser::token::BEFORE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"begin", pgcpp_parser::BisonParser::token::BEGIN_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"between", pgcpp_parser::BisonParser::token::BETWEEN, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"bigint", pgcpp_parser::BisonParser::token::BIGINT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"binary", pgcpp_parser::BisonParser::token::BINARY, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"bit", pgcpp_parser::BisonParser::token::BIT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"boolean", pgcpp_parser::BisonParser::token::BOOLEAN_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"both", pgcpp_parser::BisonParser::token::BOTH, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"breadth", pgcpp_parser::BisonParser::token::BREADTH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"by", pgcpp_parser::BisonParser::token::BY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cache", pgcpp_parser::BisonParser::token::CACHE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"call", pgcpp_parser::BisonParser::token::CALL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"called", pgcpp_parser::BisonParser::token::CALLED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cascade", pgcpp_parser::BisonParser::token::CASCADE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cascaded", pgcpp_parser::BisonParser::token::CASCADED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"case", pgcpp_parser::BisonParser::token::CASE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"cast", pgcpp_parser::BisonParser::token::CAST, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"catalog", pgcpp_parser::BisonParser::token::CATALOG_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"chain", pgcpp_parser::BisonParser::token::CHAIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"char", pgcpp_parser::BisonParser::token::CHAR_P, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"character", pgcpp_parser::BisonParser::token::CHARACTER, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"characteristics", pgcpp_parser::BisonParser::token::CHARACTERISTICS,
     KeywordCategory::kUnreserved, KeywordLabel::kBareLabel},
    {"check", pgcpp_parser::BisonParser::token::CHECK, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"checkpoint", pgcpp_parser::BisonParser::token::CHECKPOINT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"class", pgcpp_parser::BisonParser::token::CLASS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"close", pgcpp_parser::BisonParser::token::CLOSE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cluster", pgcpp_parser::BisonParser::token::CLUSTER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"coalesce", pgcpp_parser::BisonParser::token::COALESCE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"collate", pgcpp_parser::BisonParser::token::COLLATE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"collation", pgcpp_parser::BisonParser::token::COLLATION, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"column", pgcpp_parser::BisonParser::token::COLUMN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"columns", pgcpp_parser::BisonParser::token::COLUMNS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"comment", pgcpp_parser::BisonParser::token::COMMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"comments", pgcpp_parser::BisonParser::token::COMMENTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"commit", pgcpp_parser::BisonParser::token::COMMIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"committed", pgcpp_parser::BisonParser::token::COMMITTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"compression", pgcpp_parser::BisonParser::token::COMPRESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"concurrently", pgcpp_parser::BisonParser::token::CONCURRENTLY, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"configuration", pgcpp_parser::BisonParser::token::CONFIGURATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"conflict", pgcpp_parser::BisonParser::token::CONFLICT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"connection", pgcpp_parser::BisonParser::token::CONNECTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"constraint", pgcpp_parser::BisonParser::token::CONSTRAINT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"constraints", pgcpp_parser::BisonParser::token::CONSTRAINTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"content", pgcpp_parser::BisonParser::token::CONTENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"continue", pgcpp_parser::BisonParser::token::CONTINUE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"conversion", pgcpp_parser::BisonParser::token::CONVERSION_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"copy", pgcpp_parser::BisonParser::token::COPY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cost", pgcpp_parser::BisonParser::token::COST, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"create", pgcpp_parser::BisonParser::token::CREATE, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"createdb", pgcpp_parser::BisonParser::token::CREATEDB, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"createrole", pgcpp_parser::BisonParser::token::CREATEROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cross", pgcpp_parser::BisonParser::token::CROSS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"csv", pgcpp_parser::BisonParser::token::CSV, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cube", pgcpp_parser::BisonParser::token::CUBE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"current", pgcpp_parser::BisonParser::token::CURRENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"current_catalog", pgcpp_parser::BisonParser::token::CURRENT_CATALOG,
     KeywordCategory::kReserved, KeywordLabel::kBareLabel},
    {"current_date", pgcpp_parser::BisonParser::token::CURRENT_DATE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_role", pgcpp_parser::BisonParser::token::CURRENT_ROLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_schema", pgcpp_parser::BisonParser::token::CURRENT_SCHEMA,
     KeywordCategory::kTypeFuncName, KeywordLabel::kBareLabel},
    {"current_time", pgcpp_parser::BisonParser::token::CURRENT_TIME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"current_timestamp", pgcpp_parser::BisonParser::token::CURRENT_TIMESTAMP,
     KeywordCategory::kReserved, KeywordLabel::kBareLabel},
    {"current_user", pgcpp_parser::BisonParser::token::CURRENT_USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"cursor", pgcpp_parser::BisonParser::token::CURSOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"cycle", pgcpp_parser::BisonParser::token::CYCLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"data", pgcpp_parser::BisonParser::token::DATA_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"database", pgcpp_parser::BisonParser::token::DATABASE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"day", pgcpp_parser::BisonParser::token::DAY_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"deallocate", pgcpp_parser::BisonParser::token::DEALLOCATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"dec", pgcpp_parser::BisonParser::token::DEC, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"decimal", pgcpp_parser::BisonParser::token::DECIMAL_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"declare", pgcpp_parser::BisonParser::token::DECLARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"default", pgcpp_parser::BisonParser::token::DEFAULT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"defaults", pgcpp_parser::BisonParser::token::DEFAULTS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"deferrable", pgcpp_parser::BisonParser::token::DEFERRABLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"deferred", pgcpp_parser::BisonParser::token::DEFERRED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"definer", pgcpp_parser::BisonParser::token::DEFINER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delete", pgcpp_parser::BisonParser::token::DELETE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delimiter", pgcpp_parser::BisonParser::token::DELIMITER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"delimiters", pgcpp_parser::BisonParser::token::DELIMITERS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"depends", pgcpp_parser::BisonParser::token::DEPENDS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"depth", pgcpp_parser::BisonParser::token::DEPTH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"desc", pgcpp_parser::BisonParser::token::DESC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"detach", pgcpp_parser::BisonParser::token::DETACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"dictionary", pgcpp_parser::BisonParser::token::DICTIONARY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"disable", pgcpp_parser::BisonParser::token::DISABLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"discard", pgcpp_parser::BisonParser::token::DISCARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"distinct", pgcpp_parser::BisonParser::token::DISTINCT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"do", pgcpp_parser::BisonParser::token::DO, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"document", pgcpp_parser::BisonParser::token::DOCUMENT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"domain", pgcpp_parser::BisonParser::token::DOMAIN_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"double", pgcpp_parser::BisonParser::token::DOUBLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"drop", pgcpp_parser::BisonParser::token::DROP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"each", pgcpp_parser::BisonParser::token::EACH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"else", pgcpp_parser::BisonParser::token::ELSE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"enable", pgcpp_parser::BisonParser::token::ENABLE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"encoding", pgcpp_parser::BisonParser::token::ENCODING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"encrypted", pgcpp_parser::BisonParser::token::ENCRYPTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"end", pgcpp_parser::BisonParser::token::END_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"enum", pgcpp_parser::BisonParser::token::ENUM_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"escape", pgcpp_parser::BisonParser::token::ESCAPE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"event", pgcpp_parser::BisonParser::token::EVENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"except", pgcpp_parser::BisonParser::token::EXCEPT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"exclude", pgcpp_parser::BisonParser::token::EXCLUDE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"excluding", pgcpp_parser::BisonParser::token::EXCLUDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"exclusive", pgcpp_parser::BisonParser::token::EXCLUSIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"execute", pgcpp_parser::BisonParser::token::EXECUTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"exists", pgcpp_parser::BisonParser::token::EXISTS, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"explain", pgcpp_parser::BisonParser::token::EXPLAIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"expression", pgcpp_parser::BisonParser::token::EXPRESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"extension", pgcpp_parser::BisonParser::token::EXTENSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"external", pgcpp_parser::BisonParser::token::EXTERNAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"extract", pgcpp_parser::BisonParser::token::EXTRACT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"false", pgcpp_parser::BisonParser::token::FALSE_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"family", pgcpp_parser::BisonParser::token::FAMILY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"fetch", pgcpp_parser::BisonParser::token::FETCH, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"filter", pgcpp_parser::BisonParser::token::FILTER, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"finalize", pgcpp_parser::BisonParser::token::FINALIZE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"first", pgcpp_parser::BisonParser::token::FIRST_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"float", pgcpp_parser::BisonParser::token::FLOAT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"following", pgcpp_parser::BisonParser::token::FOLLOWING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"for", pgcpp_parser::BisonParser::token::FOR, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"force", pgcpp_parser::BisonParser::token::FORCE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"foreign", pgcpp_parser::BisonParser::token::FOREIGN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"forward", pgcpp_parser::BisonParser::token::FORWARD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"freeze", pgcpp_parser::BisonParser::token::FREEZE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"from", pgcpp_parser::BisonParser::token::FROM, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"full", pgcpp_parser::BisonParser::token::FULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"function", pgcpp_parser::BisonParser::token::FUNCTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"functions", pgcpp_parser::BisonParser::token::FUNCTIONS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"generated", pgcpp_parser::BisonParser::token::GENERATED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"global", pgcpp_parser::BisonParser::token::GLOBAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"grant", pgcpp_parser::BisonParser::token::GRANT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"granted", pgcpp_parser::BisonParser::token::GRANTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"greatest", pgcpp_parser::BisonParser::token::GREATEST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"group", pgcpp_parser::BisonParser::token::GROUP_P, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"grouping", pgcpp_parser::BisonParser::token::GROUPING, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"groups", pgcpp_parser::BisonParser::token::GROUPS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"handler", pgcpp_parser::BisonParser::token::HANDLER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"having", pgcpp_parser::BisonParser::token::HAVING, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"header", pgcpp_parser::BisonParser::token::HEADER_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"hold", pgcpp_parser::BisonParser::token::HOLD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"hour", pgcpp_parser::BisonParser::token::HOUR_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"identity", pgcpp_parser::BisonParser::token::IDENTITY_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"if", pgcpp_parser::BisonParser::token::IF_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"ilike", pgcpp_parser::BisonParser::token::ILIKE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"immediate", pgcpp_parser::BisonParser::token::IMMEDIATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"immutable", pgcpp_parser::BisonParser::token::IMMUTABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"implicit", pgcpp_parser::BisonParser::token::IMPLICIT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"import", pgcpp_parser::BisonParser::token::IMPORT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"in", pgcpp_parser::BisonParser::token::IN_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"include", pgcpp_parser::BisonParser::token::INCLUDE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"including", pgcpp_parser::BisonParser::token::INCLUDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"increment", pgcpp_parser::BisonParser::token::INCREMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"index", pgcpp_parser::BisonParser::token::INDEX, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"indexes", pgcpp_parser::BisonParser::token::INDEXES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inherit", pgcpp_parser::BisonParser::token::INHERIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inherits", pgcpp_parser::BisonParser::token::INHERITS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"initially", pgcpp_parser::BisonParser::token::INITIALLY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"inline", pgcpp_parser::BisonParser::token::INLINE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"inner", pgcpp_parser::BisonParser::token::INNER_P, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"inout", pgcpp_parser::BisonParser::token::INOUT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"input", pgcpp_parser::BisonParser::token::INPUT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"insensitive", pgcpp_parser::BisonParser::token::INSENSITIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"insert", pgcpp_parser::BisonParser::token::INSERT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"instead", pgcpp_parser::BisonParser::token::INSTEAD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"int", pgcpp_parser::BisonParser::token::INT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"integer", pgcpp_parser::BisonParser::token::INTEGER, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"intersect", pgcpp_parser::BisonParser::token::INTERSECT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"interval", pgcpp_parser::BisonParser::token::INTERVAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"into", pgcpp_parser::BisonParser::token::INTO, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"invoker", pgcpp_parser::BisonParser::token::INVOKER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"is", pgcpp_parser::BisonParser::token::IS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"isnull", pgcpp_parser::BisonParser::token::ISNULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"isolation", pgcpp_parser::BisonParser::token::ISOLATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"join", pgcpp_parser::BisonParser::token::JOIN, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"key", pgcpp_parser::BisonParser::token::KEY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"label", pgcpp_parser::BisonParser::token::LABEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"language", pgcpp_parser::BisonParser::token::LANGUAGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"large", pgcpp_parser::BisonParser::token::LARGE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"last", pgcpp_parser::BisonParser::token::LAST_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"lateral", pgcpp_parser::BisonParser::token::LATERAL_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"leading", pgcpp_parser::BisonParser::token::LEADING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"leakproof", pgcpp_parser::BisonParser::token::LEAKPROOF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"least", pgcpp_parser::BisonParser::token::LEAST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"left", pgcpp_parser::BisonParser::token::LEFT, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"level", pgcpp_parser::BisonParser::token::LEVEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"like", pgcpp_parser::BisonParser::token::LIKE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"limit", pgcpp_parser::BisonParser::token::LIMIT, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"listen", pgcpp_parser::BisonParser::token::LISTEN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"load", pgcpp_parser::BisonParser::token::LOAD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"local", pgcpp_parser::BisonParser::token::LOCAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"localtime", pgcpp_parser::BisonParser::token::LOCALTIME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"localtimestamp", pgcpp_parser::BisonParser::token::LOCALTIMESTAMP, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"location", pgcpp_parser::BisonParser::token::LOCATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"lock", pgcpp_parser::BisonParser::token::LOCK_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"locked", pgcpp_parser::BisonParser::token::LOCKED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"logged", pgcpp_parser::BisonParser::token::LOGGED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"login", pgcpp_parser::BisonParser::token::LOGIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"mapping", pgcpp_parser::BisonParser::token::MAPPING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"match", pgcpp_parser::BisonParser::token::MATCH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"matched", pgcpp_parser::BisonParser::token::MATCHED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"materialized", pgcpp_parser::BisonParser::token::MATERIALIZED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"maxvalue", pgcpp_parser::BisonParser::token::MAXVALUE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"merge", pgcpp_parser::BisonParser::token::MERGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"method", pgcpp_parser::BisonParser::token::METHOD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"minute", pgcpp_parser::BisonParser::token::MINUTE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"minvalue", pgcpp_parser::BisonParser::token::MINVALUE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"mode", pgcpp_parser::BisonParser::token::MODE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"month", pgcpp_parser::BisonParser::token::MONTH_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"move", pgcpp_parser::BisonParser::token::MOVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"name", pgcpp_parser::BisonParser::token::NAME_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"names", pgcpp_parser::BisonParser::token::NAMES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"national", pgcpp_parser::BisonParser::token::NATIONAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"natural", pgcpp_parser::BisonParser::token::NATURAL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"nchar", pgcpp_parser::BisonParser::token::NCHAR, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"new", pgcpp_parser::BisonParser::token::NEW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"next", pgcpp_parser::BisonParser::token::NEXT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfc", pgcpp_parser::BisonParser::token::NFC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfd", pgcpp_parser::BisonParser::token::NFD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfkc", pgcpp_parser::BisonParser::token::NFKC, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nfkd", pgcpp_parser::BisonParser::token::NFKD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"no", pgcpp_parser::BisonParser::token::NO, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nocreatedb", pgcpp_parser::BisonParser::token::NOCREATEDB, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nocreaterole", pgcpp_parser::BisonParser::token::NOCREATEROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"noreplication", pgcpp_parser::BisonParser::token::NOREPLICATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"nosuperuser", pgcpp_parser::BisonParser::token::NOSUPERUSER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"none", pgcpp_parser::BisonParser::token::NONE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"normalize", pgcpp_parser::BisonParser::token::NORMALIZE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"normalized", pgcpp_parser::BisonParser::token::NORMALIZED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"not", pgcpp_parser::BisonParser::token::NOT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"nothing", pgcpp_parser::BisonParser::token::NOTHING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"notify", pgcpp_parser::BisonParser::token::NOTIFY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"notnull", pgcpp_parser::BisonParser::token::NOTNULL, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"nowait", pgcpp_parser::BisonParser::token::NOWAIT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"null", pgcpp_parser::BisonParser::token::NULL_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"nullif", pgcpp_parser::BisonParser::token::NULLIF, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"nulls", pgcpp_parser::BisonParser::token::NULLS_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"numeric", pgcpp_parser::BisonParser::token::NUMERIC, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"object", pgcpp_parser::BisonParser::token::OBJECT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"of", pgcpp_parser::BisonParser::token::OF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"off", pgcpp_parser::BisonParser::token::OFF, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"offset", pgcpp_parser::BisonParser::token::OFFSET, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"oids", pgcpp_parser::BisonParser::token::OIDS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"old", pgcpp_parser::BisonParser::token::OLD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"on", pgcpp_parser::BisonParser::token::ON, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"only", pgcpp_parser::BisonParser::token::ONLY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"operator", pgcpp_parser::BisonParser::token::OPERATOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"option", pgcpp_parser::BisonParser::token::OPTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"options", pgcpp_parser::BisonParser::token::OPTIONS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"or", pgcpp_parser::BisonParser::token::OR, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"order", pgcpp_parser::BisonParser::token::ORDER, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"ordinality", pgcpp_parser::BisonParser::token::ORDINALITY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"others", pgcpp_parser::BisonParser::token::OTHERS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"out", pgcpp_parser::BisonParser::token::OUT_P, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"outer", pgcpp_parser::BisonParser::token::OUTER_P, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"over", pgcpp_parser::BisonParser::token::OVER, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"overlaps", pgcpp_parser::BisonParser::token::OVERLAPS, KeywordCategory::kTypeFuncName,
     KeywordLabel::kAsLabel},
    {"overlay", pgcpp_parser::BisonParser::token::OVERLAY, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"overriding", pgcpp_parser::BisonParser::token::OVERRIDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"owned", pgcpp_parser::BisonParser::token::OWNED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"owner", pgcpp_parser::BisonParser::token::OWNER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parallel", pgcpp_parser::BisonParser::token::PARALLEL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parameter", pgcpp_parser::BisonParser::token::PARAMETER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"parser", pgcpp_parser::BisonParser::token::PARSER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"partial", pgcpp_parser::BisonParser::token::PARTIAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"partition", pgcpp_parser::BisonParser::token::PARTITION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"passing", pgcpp_parser::BisonParser::token::PASSING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"password", pgcpp_parser::BisonParser::token::PASSWORD, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"permissive", pgcpp_parser::BisonParser::token::PERMISSIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"placing", pgcpp_parser::BisonParser::token::PLACING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"plans", pgcpp_parser::BisonParser::token::PLANS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"policy", pgcpp_parser::BisonParser::token::POLICY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"position", pgcpp_parser::BisonParser::token::POSITION, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"preceding", pgcpp_parser::BisonParser::token::PRECEDING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"precision", pgcpp_parser::BisonParser::token::PRECISION, KeywordCategory::kColName,
     KeywordLabel::kAsLabel},
    {"prepare", pgcpp_parser::BisonParser::token::PREPARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"prepared", pgcpp_parser::BisonParser::token::PREPARED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"preserve", pgcpp_parser::BisonParser::token::PRESERVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"primary", pgcpp_parser::BisonParser::token::PRIMARY, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"prior", pgcpp_parser::BisonParser::token::PRIOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"privileges", pgcpp_parser::BisonParser::token::PRIVILEGES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedural", pgcpp_parser::BisonParser::token::PROCEDURAL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedure", pgcpp_parser::BisonParser::token::PROCEDURE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"procedures", pgcpp_parser::BisonParser::token::PROCEDURES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"program", pgcpp_parser::BisonParser::token::PROGRAM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"publication", pgcpp_parser::BisonParser::token::PUBLICATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"quote", pgcpp_parser::BisonParser::token::QUOTE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"range", pgcpp_parser::BisonParser::token::RANGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"read", pgcpp_parser::BisonParser::token::READ, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"real", pgcpp_parser::BisonParser::token::REAL, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"reassign", pgcpp_parser::BisonParser::token::REASSIGN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"recheck", pgcpp_parser::BisonParser::token::RECHECK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"recursive", pgcpp_parser::BisonParser::token::RECURSIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"ref", pgcpp_parser::BisonParser::token::REF_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"references", pgcpp_parser::BisonParser::token::REFERENCES, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"referencing", pgcpp_parser::BisonParser::token::REFERENCING, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"refresh", pgcpp_parser::BisonParser::token::REFRESH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"reindex", pgcpp_parser::BisonParser::token::REINDEX, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"relative", pgcpp_parser::BisonParser::token::RELATIVE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"release", pgcpp_parser::BisonParser::token::RELEASE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rename", pgcpp_parser::BisonParser::token::RENAME, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"repeatable", pgcpp_parser::BisonParser::token::REPEATABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replace", pgcpp_parser::BisonParser::token::REPLACE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replica", pgcpp_parser::BisonParser::token::REPLICA, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"replication", pgcpp_parser::BisonParser::token::REPLICATION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"reset", pgcpp_parser::BisonParser::token::RESET, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"restart", pgcpp_parser::BisonParser::token::RESTART, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"restrict", pgcpp_parser::BisonParser::token::RESTRICT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"restrictive", pgcpp_parser::BisonParser::token::RESTRICTIVE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"return", pgcpp_parser::BisonParser::token::RETURN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"returning", pgcpp_parser::BisonParser::token::RETURNING, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"returns", pgcpp_parser::BisonParser::token::RETURNS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"revoke", pgcpp_parser::BisonParser::token::REVOKE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"right", pgcpp_parser::BisonParser::token::RIGHT, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"role", pgcpp_parser::BisonParser::token::ROLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rollback", pgcpp_parser::BisonParser::token::ROLLBACK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rollup", pgcpp_parser::BisonParser::token::ROLLUP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"routine", pgcpp_parser::BisonParser::token::ROUTINE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"routines", pgcpp_parser::BisonParser::token::ROUTINES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"row", pgcpp_parser::BisonParser::token::ROW, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"rows", pgcpp_parser::BisonParser::token::ROWS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"rule", pgcpp_parser::BisonParser::token::RULE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"savepoint", pgcpp_parser::BisonParser::token::SAVEPOINT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"schema", pgcpp_parser::BisonParser::token::SCHEMA, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"schemas", pgcpp_parser::BisonParser::token::SCHEMAS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"scroll", pgcpp_parser::BisonParser::token::SCROLL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"search", pgcpp_parser::BisonParser::token::SEARCH, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"second", pgcpp_parser::BisonParser::token::SECOND_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"security", pgcpp_parser::BisonParser::token::SECURITY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"select", pgcpp_parser::BisonParser::token::SELECT, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sequence", pgcpp_parser::BisonParser::token::SEQUENCE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"sequences", pgcpp_parser::BisonParser::token::SEQUENCES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"serializable", pgcpp_parser::BisonParser::token::SERIALIZABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"server", pgcpp_parser::BisonParser::token::SERVER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"session", pgcpp_parser::BisonParser::token::SESSION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"session_user", pgcpp_parser::BisonParser::token::SESSION_USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"set", pgcpp_parser::BisonParser::token::SET, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"setof", pgcpp_parser::BisonParser::token::SETOF, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"sets", pgcpp_parser::BisonParser::token::SETS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"share", pgcpp_parser::BisonParser::token::SHARE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"show", pgcpp_parser::BisonParser::token::SHOW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"similar", pgcpp_parser::BisonParser::token::SIMILAR, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"simple", pgcpp_parser::BisonParser::token::SIMPLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"skip", pgcpp_parser::BisonParser::token::SKIP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"smallint", pgcpp_parser::BisonParser::token::SMALLINT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"snapshot", pgcpp_parser::BisonParser::token::SNAPSHOT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"some", pgcpp_parser::BisonParser::token::SOME, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sql", pgcpp_parser::BisonParser::token::SQL_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stable", pgcpp_parser::BisonParser::token::STABLE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"standalone", pgcpp_parser::BisonParser::token::STANDALONE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"start", pgcpp_parser::BisonParser::token::START, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"statement", pgcpp_parser::BisonParser::token::STATEMENT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"statistics", pgcpp_parser::BisonParser::token::STATISTICS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stdin", pgcpp_parser::BisonParser::token::STDIN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stdout", pgcpp_parser::BisonParser::token::STDOUT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"storage", pgcpp_parser::BisonParser::token::STORAGE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"stored", pgcpp_parser::BisonParser::token::STORED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"strict", pgcpp_parser::BisonParser::token::STRICT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"strip", pgcpp_parser::BisonParser::token::STRIP_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"subscription", pgcpp_parser::BisonParser::token::SUBSCRIPTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"substring", pgcpp_parser::BisonParser::token::SUBSTRING, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"support", pgcpp_parser::BisonParser::token::SUPPORT, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"superuser", pgcpp_parser::BisonParser::token::SUPERUSER_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"symmetric", pgcpp_parser::BisonParser::token::SYMMETRIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"sysid", pgcpp_parser::BisonParser::token::SYSID, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"system", pgcpp_parser::BisonParser::token::SYSTEM_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"table", pgcpp_parser::BisonParser::token::TABLE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"tables", pgcpp_parser::BisonParser::token::TABLES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"tablesample", pgcpp_parser::BisonParser::token::TABLESAMPLE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"tablespace", pgcpp_parser::BisonParser::token::TABLESPACE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"temp", pgcpp_parser::BisonParser::token::TEMP, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"template", pgcpp_parser::BisonParser::token::TEMPLATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"temporary", pgcpp_parser::BisonParser::token::TEMPORARY, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"text", pgcpp_parser::BisonParser::token::TEXT_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"then", pgcpp_parser::BisonParser::token::THEN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"ties", pgcpp_parser::BisonParser::token::TIES, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"time", pgcpp_parser::BisonParser::token::TIME, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"timestamp", pgcpp_parser::BisonParser::token::TIMESTAMP, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"to", pgcpp_parser::BisonParser::token::TO, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"trailing", pgcpp_parser::BisonParser::token::TRAILING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"transaction", pgcpp_parser::BisonParser::token::TRANSACTION, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"transform", pgcpp_parser::BisonParser::token::TRANSFORM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"treat", pgcpp_parser::BisonParser::token::TREAT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"trigger", pgcpp_parser::BisonParser::token::TRIGGER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"trim", pgcpp_parser::BisonParser::token::TRIM, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"true", pgcpp_parser::BisonParser::token::TRUE_P, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"truncate", pgcpp_parser::BisonParser::token::TRUNCATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"trusted", pgcpp_parser::BisonParser::token::TRUSTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"type", pgcpp_parser::BisonParser::token::TYPE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"types", pgcpp_parser::BisonParser::token::TYPES_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"uescape", pgcpp_parser::BisonParser::token::UESCAPE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unbounded", pgcpp_parser::BisonParser::token::UNBOUNDED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"uncommitted", pgcpp_parser::BisonParser::token::UNCOMMITTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unencrypted", pgcpp_parser::BisonParser::token::UNENCRYPTED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"union", pgcpp_parser::BisonParser::token::UNION, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"unique", pgcpp_parser::BisonParser::token::UNIQUE, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"unknown", pgcpp_parser::BisonParser::token::UNKNOWN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unlisten", pgcpp_parser::BisonParser::token::UNLISTEN, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"unlogged", pgcpp_parser::BisonParser::token::UNLOGGED, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"until", pgcpp_parser::BisonParser::token::UNTIL, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"update", pgcpp_parser::BisonParser::token::UPDATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"user", pgcpp_parser::BisonParser::token::USER, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"using", pgcpp_parser::BisonParser::token::USING, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"vacuum", pgcpp_parser::BisonParser::token::VACUUM, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"valid", pgcpp_parser::BisonParser::token::VALID, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"validate", pgcpp_parser::BisonParser::token::VALIDATE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"validator", pgcpp_parser::BisonParser::token::VALIDATOR, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"value", pgcpp_parser::BisonParser::token::VALUE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"values", pgcpp_parser::BisonParser::token::VALUES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"varchar", pgcpp_parser::BisonParser::token::VARCHAR, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"variadic", pgcpp_parser::BisonParser::token::VARIADIC, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"varying", pgcpp_parser::BisonParser::token::VARYING, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"verbose", pgcpp_parser::BisonParser::token::VERBOSE, KeywordCategory::kTypeFuncName,
     KeywordLabel::kBareLabel},
    {"version", pgcpp_parser::BisonParser::token::VERSION_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"view", pgcpp_parser::BisonParser::token::VIEW, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"views", pgcpp_parser::BisonParser::token::VIEWS, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"volatile", pgcpp_parser::BisonParser::token::VOLATILE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"when", pgcpp_parser::BisonParser::token::WHEN, KeywordCategory::kReserved,
     KeywordLabel::kBareLabel},
    {"where", pgcpp_parser::BisonParser::token::WHERE, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"whitespace", pgcpp_parser::BisonParser::token::WHITESPACE_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"window", pgcpp_parser::BisonParser::token::WINDOW, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"with", pgcpp_parser::BisonParser::token::WITH, KeywordCategory::kReserved,
     KeywordLabel::kAsLabel},
    {"within", pgcpp_parser::BisonParser::token::WITHIN, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"without", pgcpp_parser::BisonParser::token::WITHOUT, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"work", pgcpp_parser::BisonParser::token::WORK, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"wrapper", pgcpp_parser::BisonParser::token::WRAPPER, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"write", pgcpp_parser::BisonParser::token::WRITE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"xml", pgcpp_parser::BisonParser::token::XML_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"xmlattributes", pgcpp_parser::BisonParser::token::XMLATTRIBUTES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlconcat", pgcpp_parser::BisonParser::token::XMLCONCAT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlelement", pgcpp_parser::BisonParser::token::XMLELEMENT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlexists", pgcpp_parser::BisonParser::token::XMLEXISTS, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlforest", pgcpp_parser::BisonParser::token::XMLFOREST, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlnamespaces", pgcpp_parser::BisonParser::token::XMLNAMESPACES, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlparse", pgcpp_parser::BisonParser::token::XMLPARSE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlpi", pgcpp_parser::BisonParser::token::XMLPI, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlroot", pgcpp_parser::BisonParser::token::XMLROOT, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmlserialize", pgcpp_parser::BisonParser::token::XMLSERIALIZE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"xmltable", pgcpp_parser::BisonParser::token::XMLTABLE, KeywordCategory::kColName,
     KeywordLabel::kBareLabel},
    {"year", pgcpp_parser::BisonParser::token::YEAR_P, KeywordCategory::kUnreserved,
     KeywordLabel::kAsLabel},
    {"yes", pgcpp_parser::BisonParser::token::YES_P, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
    {"zone", pgcpp_parser::BisonParser::token::ZONE, KeywordCategory::kUnreserved,
     KeywordLabel::kBareLabel},
};

const KeywordEntry* ScanKeywordLookup(std::string_view name) {
    int lo = 0, hi = kKeywordCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = name.compare(kKeywordTable[mid].name);
        if (cmp == 0)
            return &kKeywordTable[mid];
        if (cmp < 0)
            hi = mid - 1;
        else
            lo = mid + 1;
    }
    return nullptr;
}

}  // namespace pgcpp::parser
